  on:
    push:
      branches:
        - master




  jobs:
    build:
      runs-on: ubuntu-latest


      steps:
        - uses: actions/checkout@v3

        - name: "printing folder content"
          run: ls

        - name: "login to Docker hub" 
          run: docker login --username ${{ secrets.MARIAM_REDA_MOHAMED_2023040387 }} --password ${{ secrets.MARIAM_REDA_MOHAMED_PASS_2023040387 }}

        - name: "building image"
          run: docker build -t ${{ secrets.MARIAM_REDA_MOHAMED_2023040387 }}/Mariam_Reda_Mohamed_2023040387_image .

        - name: "pushing to docker hub"  
          run: docker push ${{ secrets.MARIAM_REDA_MOHAMED_2023040387 }}/Mariam_Reda_Mohamed_2023040387_image 




